### ISSUE TITLE
External links in SVGs are destroyed utterly by the sanitisation function

### ISSUE THREAD

**Issue by richplane** [castlegateit/monolith#1]
The sanitisation function makes IDs and classes unique by suffixing a hash. It also does this to hrefs, but these could be a link to an external resource rather than something in the SVG which should be made distinct.

SImplest fix I can think of is to change modifyAttributes so that it skips over external links in the same way as it does empty attributes:

```
    if (!$value || substr($value,0,4)=='http') {
        continue;
    }
```
(lines 196-198 of ScaleableVectorGraphic.php).

**Comment by johnkhughes** [comment]
I've gone with checking for "#" instead of "http", but the effect is the same. Should be working now.

**Comment by richplane** [comment]
Yeah that makes more sense, in retrospect, because links could start with the protocol agnostic // or probably links relative to the domain root
